[package]
name = "apple_notes_rs_bin"
version = "0.3.4"
authors = ["Findus"]
autobins = false

[dependencies]
log = "0.4"
clap = "2.33.1"
colored = "2"
serde_json = "1.0.56"
serde_derive = "1.0.114"
serde = "1.0.114"
diesel = { features = ["sqlite"], version =  "1.4.5"}
itertools = "0.10.0"
flexi_logger = "0.17"

apple_notes_manager = { path = "../lib" }


[[bin]]
name = "backup"
path = "bin/backup.rs"

[[bin]]
name = "apnotes"
path = "bin/notes.rs"