[package]
name = "apple_notes_rs_ui_iced"
version = "0.0.2"
authors = ["Findus"]
autobins = false

[dependencies]
apple_notes_rs_lib = { path = "../lib" }
iced = { version = "0.1.1", features = ["canvas", "tokio", "debug"] }
chrono = "0.4"

[[bin]]
name = "ui_iced"
path = "./src/ui.rs"
